export type { CustomCSSProperties } from './customCSSProperties'
export type { LanguageCode } from './supportedLanguages'
export { KeyboardKeys } from './keyboardKeys'
export { SUPPORTED_LANGUAGES } from './supportedLanguages'
export { GameColors } from './gameColors'
