import ruWords from '../../../public/dictionaries/ru.json'
import enWords from '../../../public/dictionaries/en.json'

export enum LanguageCode {
    ru = 'ru',
    en = 'en',
}

export const SUPPORTED_LANGUAGES = {
    [LanguageCode.ru]: {
        label: 'ру',
        words: ruWords,
        regex: /^[а-яА-ЯёЁ]$/,
        keyboard: [
            [
                { code: 'й', label: 'й', type: 'char' },
                { code: 'ц', label: 'ц', type: 'char' },
                { code: 'у', label: 'у', type: 'char' },
                { code: 'к', label: 'к', type: 'char' },
                { code: 'е', label: 'е', type: 'char' },
                { code: 'н', label: 'н', type: 'char' },
                { code: 'г', label: 'г', type: 'char' },
                { code: 'ш', label: 'ш', type: 'char' },
                { code: 'щ', label: 'щ', type: 'char' },
                { code: 'з', label: 'з', type: 'char' },
                { code: 'х', label: 'х', type: 'char' },
                { code: 'ъ', label: 'ъ', type: 'char' },
            ],
            [
                { code: 'ф', label: 'ф', type: 'char' },
                { code: 'ы', label: 'ы', type: 'char' },
                { code: 'в', label: 'в', type: 'char' },
                { code: 'а', label: 'а', type: 'char' },
                { code: 'п', label: 'п', type: 'char' },
                { code: 'р', label: 'р', type: 'char' },
                { code: 'о', label: 'о', type: 'char' },
                { code: 'л', label: 'л', type: 'char' },
                { code: 'д', label: 'д', type: 'char' },
                { code: 'ж', label: 'ж', type: 'char' },
                { code: 'э', label: 'э', type: 'char' },
            ],
            [
                { code: 'Backspace', label: '←', type: 'action' },
                { code: 'я', label: 'я', type: 'char' },
                { code: 'ч', label: 'ч', type: 'char' },
                { code: 'с', label: 'с', type: 'char' },
                { code: 'м', label: 'м', type: 'char' },
                { code: 'и', label: 'и', type: 'char' },
                { code: 'т', label: 'т', type: 'char' },
                { code: 'ь', label: 'ь', type: 'char' },
                { code: 'б', label: 'б', type: 'char' },
                { code: 'ю', label: 'ю', type: 'char' },
                { code: 'Enter', label: 'Ввод', type: 'action' },
            ],
        ],
    },
    [LanguageCode.en]: {
        label: 'en',
        words: enWords,
        regex: /^[a-zA-Z]$/,
        keyboard: [
            [
                { code: 'q', label: 'q', type: 'char' },
                { code: 'w', label: 'w', type: 'char' },
                { code: 'e', label: 'e', type: 'char' },
                { code: 'r', label: 'r', type: 'char' },
                { code: 't', label: 't', type: 'char' },
                { code: 'y', label: 'y', type: 'char' },
                { code: 'u', label: 'u', type: 'char' },
                { code: 'i', label: 'i', type: 'char' },
                { code: 'o', label: 'o', type: 'char' },
                { code: 'p', label: 'p', type: 'char' },
            ],
            [
                { code: 'a', label: 'a', type: 'char' },
                { code: 's', label: 's', type: 'char' },
                { code: 'd', label: 'd', type: 'char' },
                { code: 'f', label: 'f', type: 'char' },
                { code: 'g', label: 'g', type: 'char' },
                { code: 'h', label: 'h', type: 'char' },
                { code: 'j', label: 'j', type: 'char' },
                { code: 'k', label: 'k', type: 'char' },
                { code: 'l', label: 'l', type: 'char' },
            ],
            [
                { code: 'Backspace', label: '←', type: 'action' },
                { code: 'z', label: 'z', type: 'char' },
                { code: 'x', label: 'x', type: 'char' },
                { code: 'c', label: 'c', type: 'char' },
                { code: 'v', label: 'v', type: 'char' },
                { code: 'b', label: 'b', type: 'char' },
                { code: 'n', label: 'n', type: 'char' },
                { code: 'm', label: 'm', type: 'char' },
                { code: 'Enter', label: 'Enter', type: 'action' },
            ],
        ],
    },
}
